ALTER TABLE "message_blocks"
  ALTER COLUMN "orderIndex" TYPE DOUBLE PRECISION USING "orderIndex"::DOUBLE PRECISION,
  ADD COLUMN "isDeleted" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "deletedAt" TIMESTAMP(3),
  ADD COLUMN "isAdded" BOOLEAN NOT NULL DEFAULT false;
